### ISSUE TITLE
Avatar creation creates too many nodes per directory

### ISSUE THREAD

**Issue by dgouldin** [grantmcconnaughey/django-avatar#10]
If AVATAR_HASH_USERDIRNAMES = False, directory-per-user will be created in AVATAR_STORAGE_DIR.  When AVATAR_HASH_USERDIRNAMES = True it gets better, but is still directory-per-user after 2 levels of hash subdivision.  At scale, this will get out of control.  It seems like a strftime based folder structure (as encouraged by FileField) would keep nodes/directory at a manageable level.

**Comment by darklow** [comment]
I agree. As a solution it would great if `avatar_file_path` method could be configurable.
https://github.com/grantmcconnaughey/django-avatar/blob/master/avatar/models.py#L26

There is no perfect solution for everyone. If users could define their own callback, they could customise path whatever way they want. What do you think?

**Comment by darklow** [comment]
I created a pull request with a possibility to change avatar file path handler.
Now if needed users can specify their own file paths based on different criteria.
For example i am usually sepearating in subdivisions by last 2 or 3 numbers from instance ID, to make sure files are +/- similarly distributed. For example this is how I extended current path handler:

```py
# settings.py:
AVATAR_PATH_HANDLER = 'user.avatars.my_avatar_path_handler'

# user/avatars.py
from avatar.models import avatar_path_handler

def my_avatar_path_handler(instance=None, filename=None, size=None, ext=None):
    path = avatar_path_handler(instance, filename, size, ext)
    parts = path.split('/')
    parts[1] = str(instance.user_id)[-2:]
    return '/'.join(parts)

# Final path:
# avatars/21/file-name...
# avatars/02/file-name...
# avatars/73/file-name...
```

**Comment by grantmcconnaughey** [comment]
I've merged @darklow into master. I'll release 3.0 soon.

**Comment by darklow** [comment]
@grantmcconnaughey thanks!

**Comment by jacopsd** [comment]
Sorry if this is not the right place to ask but,
This AVATAR_PATH_HANDLER looks like a good solution for my multi-tenants + avatars problem:
http://stackoverflow.com/questions/41530171/django-tenant-schemas-avatars

Only issue now is: how to get access to the 'request' within that AVATAR_PATH_HANDLER?
If I can get access to the request, I can make a tenant specific path to store the avatar.

**Comment by grantmcconnaughey** [comment]
@jacopsd, the `AVATAR_PATH_HANDLER` function is not passed a request object, so the only way to get this would be through the current thread's request.

Try this blog post: http://nedbatchelder.com/blog/201008/global_django_requests.html

**Comment by jacopsd** [comment]
great, thx
