### ISSUE TITLE
When can version 2.1 be pushed to PyPi?

### ISSUE THREAD

**Issue by jennyq** [grantmcconnaughey/django-avatar#107]
The version 2.0 is the one on PyPi, but it is not compatible with Django 1.8. We'd greatly appreciate if someone can push the latest version 2.1 to PyPi https://pypi.python.org/pypi/django-avatar/. Thanks!

**Comment by grantmcconnaughey** [comment]
Hi @jennyq.

I'm hoping to get with @jezdez soon to deploy the 2.1 update to PyPI. Until then add the following to your requirements.txt to use version 2.1:

    -e git+https://github.com/jezdez/django-avatar.git@2.1#egg=django_avatar

**Comment by jennyq** [comment]
@grantmcconnaughey, thanks for the quick response! That's what we're temporarily doing. Hope it gets resolved soon.

**Comment by grantmcconnaughey** [comment]
django-avatar 2.1.1 has been released to PyPI (I skipped over releasing 2.1 because I had made some changes since then).

**Comment by jennyq** [comment]
Thanks!
