### ISSUE TITLE
Allow passing in an e-mail string instead of a user object

### ISSUE THREAD

**Issue by darkpixel** [grantmcconnaughey/django-avatar#112]
Especially when doing quick mock-ups, I'd love to be able to call ```{% avatar_url 'me@example.tld' 50 %}```

**Comment by grantmcconnaughey** [comment]
`avatar_url` calls `get_primary_avatar` which will lookup the user by their "natural key" if necessary. This means it should work just fine if you're `email` field is the User's `USERNAME_FIELD`. https://docs.djangoproject.com/en/1.9/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD
