### ISSUE TITLE
Customize the template of avatar uploading 

### ISSUE THREAD

**Issue by rylanchiu** [grantmcconnaughey/django-avatar#115]
Can I change the template of avatar uploading page? How to do that?

**Comment by jnns** [comment]
Straight from the [docs](https://django-avatar.readthedocs.io/en/latest/#global-settings):

> `AVATAR_ADD_TEMPLATE`
    Path to the Django template to use for adding a new avatar. Defaults to avatar/add.html.
`AVATAR_CHANGE_TEMPLATE`
    Path to the Django template to use for changing a user’s avatar. Defaults to avatar/change.html.
`AVATAR_DELETE_TEMPLATE`
    Path to the Django template to use for confirming a delete of a user’s avatar. Defaults to avatar/avatar/confirm_delete.html.

**Comment by grantmcconnaughey** [comment]
Thanks, @jnns. Those new settings should make this pretty easy.
