### ISSUE TITLE
Any option to call user avatar in views or models?

### ISSUE THREAD

**Issue by nordbit** [grantmcconnaughey/django-avatar#125]
Is the django-avatar only template usuable?

**Comment by grantmcconnaughey** [comment]
What exactly would you like in views/models? The avatar URL? The user's avatar instance?

**Comment by nordbit** [comment]
Avatar url
I want access to user avatar trought view or model and send to browswer trought web socket
```
class Book(models.Model):
    title = models.CharacterField()
    author = models.ForeignKey(User)

    def __str__(self):
        return '<div class="bookslist>%s - %s </div>' % (self.title, self.author)
```

and now I want add author's avatar, something like:
```
    def __str__(self):
        return '<div class="bookslist><img src="%s" />%s - %s </div>' % (self.author.get_avatar_url, self.title, self.author)
```

**Comment by grantmcconnaughey** [comment]
I see. You can use the `avatar.utils.get_primary_avatar` function to do this:

    from avatar.utils import get_primary_avatar

    def __str__(self):
        avatar = get_primary_avatar(self.author)
        return '<div class="bookslist><img src="%s" />%s - %s </div>' % (avatar.get_absolute_url(), self.title, self.author)

**Comment by nordbit** [comment]
It works. Thank You.

**Comment by nordbit** [comment]
Works partially, only when user have a uploaded image as avatar, when used is gravatar application crashed with error:
```
'NoneType' object has no attribute 'get_absolute_url'
```

**Comment by grantmcconnaughey** [comment]
You're right. Your best bet will be to use the template tag directly. That will fall back to gravatar. The avatar URL code (with Gravatar/Facebook fallbacks) probably needs to be extracted into its own function, but for now do this:

```python
from avatar.templatetags.avatar_tags import avatar_url

def __str__(self):
    return '<div class="bookslist><img src="%s" />%s - %s </div>' % (avatar_url(self.author), self.title, self.author)
```

**Comment by nordbit** [comment]
Thank You very much for your work and help.
