### ISSUE TITLE
New avatar images require new filenames

### ISSUE THREAD

**Issue by pydanny** [grantmcconnaughey/django-avatar#135]
A single user can't have the same filename in a new avatar image as an existing avatar image for that user. Possible solutions:

* Create new avatar name on upload
* Raise a Form error if a duplicate filename is used in a new image

**Comment by grantmcconnaughey** [comment]
Hey Danny!

I looked into this issue, and it looks like avatar's currently get renamed when uploaded if a file name is already taken.

The default file storage for an Avatar is Django's `FileSystemStorage`, which uses [`get_available_name`](https://docs.djangoproject.com/en/1.10/ref/files/storage/#django.core.files.storage.Storage.get_available_name) to ensure that the file name is unique.

Are you getting an error when you try to upload an avatar with the same file name? Also, are you overriding the storage class for Avatar's using the `AVATAR_STORAGE` setting? Which versions of django-avatar and Django are you using?

Grant

**Comment by pydanny** [comment]
This issue is resolved. There was a conflict with something else file related.
