### ISSUE TITLE
Image files not deleted when user delete avatar

### ISSUE THREAD

**Issue by KomeijiSatori** [grantmcconnaughey/django-avatar#152]
It seems when user delete the avatar in the front end, the database delete such record. But on the file system, the origin image still exists as well as the resized images.
So could you please also delete the useless files when deleting in the next release?

**Comment by qari** [comment]
I have same problem. Please check that

**Comment by grantmcconnaughey** [comment]
Hey there. You can change this behavior by setting the `AVATAR_CLEANUP_DELETED` to `True`. By default it is `False`, although perhaps the default behavior should be `True`.

**Comment by KomeijiSatori** [comment]
Thanks for your reply, after adding these settings, I found that the origin file and resized file in 80 is deleted,  however, in other resized folder, the image does not deleted.
So could you please follow this issue and to see whether the image could be fully deleted including the resized images?
Thank you very much!

**Comment by KomeijiSatori** [comment]
Oh, I find that, I should also set AVATAR_AUTO_GENERATE_SIZES variable, Please add this information to the doc, thank you
