### ISSUE TITLE
Invalid filter: 'has_avatar'

### ISSUE THREAD

**Issue by anuj9196** [grantmcconnaughey/django-avatar#159]
I used `{% url 'avatar_change' %}` page to change avatar and see a friendly message
```
You haven't uploaded an avatar yet. Please upload one now.
```

Since, I don't want to use a separate page for changing avatar, I'm customising own template to change avatar.

To check whether user has avatar or not
```
{{ request.user|has_avatar }}
``` 
as given in the documentation, but it gives error as
```
Invalid filter: 'has_avatar'
```

**Comment by grantmcconnaughey** [comment]
Have you included `{% load avatar_tags %}` in your template?

**Comment by anuj9196** [comment]
I had include it in base template, I thought it would work because I'm extending base template. Added in respective template and it works.

Thanks for this awesome app.
