### ISSUE TITLE
avatar_url templatetag is not cached

### ISSUE THREAD

**Issue by HoverHell** [grantmcconnaughey/django-avatar#19]
In avatar/templatetags/avatar_tags.py:17 it seems that first wrapper applied is register.simple_tag, and only then cache_result;  with that, rendering a template with many avatar_url tags is very slow since the cache is not used.

This might be problematic to fix mainly because of the default parameters;  best thing that can be done of what I found is to use a separate function that's registered as a simple_tag, and calls original function (probably renamed), which is wrapped by the cache_result.

**Comment by grantmcconnaughey** [comment]
Fixed as of 266240250a
