### ISSUE TITLE
Can not update avatar url cache completely?

### ISSUE THREAD

**Issue by allenling** [grantmcconnaughey/django-avatar#87]
e.g:
I had three sizes,  (30,30), (50,50), (80,80), update cache just delete specific avatar size,   In the nav, it called {% avatar 30 %}, and invalidate_cache just deleted (30,30) avatar, and (50,50), (80,80) would not deleted.

May be can specific all sizes configuration, e.g ALL_SIZES, in setting, and
invalidate_cache looking for ALLEN_SIZES, and delete all sizes of avatar in cache backend.

**Comment by timolson** [comment]
I also had this issue.  We use a custom size for a thumbnail in our navbar, and the cache is not invalidated for this size when the user changes their avatar.

**Comment by troyshu** [comment]
I was experiencing the same issue, then found some info in the documentation that fixed it for me. It seems to be solved by including any custom sizes in AVATAR_AUTO_GENERATE_SIZES, described at http://django-avatar.readthedocs.io/en/latest/index.html?highlight=AVATAR_AUTO_GENERATE_SIZES (leaving AVATAR_CACHE_ENABLED = True, the default). There's even a related management command for rebuilding the cached avatar sizes on command: https://github.com/grantmcconnaughey/django-avatar/commit/7d6c3f70d515282df64036eb46613a2335388bd8. @grantmcconnaughey this issue can probably be closed?

**Comment by grantmcconnaughey** [comment]
Sure thing, thanks for the heads up, @troyshu!
