### ISSUE TITLE
Code duplication for rendering an avatar

### ISSUE THREAD

**Issue by Afnarel** [grantmcconnaughey/django-avatar#99]
Hi,

The function _avatar\_img_ in forms.py is the same the function _render\_avatar_ in templatetags/avatar_tags.py, except for an optional parameter (for selecting the size) and for the _cache\_result_ decorator.

I think the template tag should call the function in forms.py to avoid code duplication.

I was looking at this because I was using the PyPI version of django-avatar and had the problem described in issue #76 and solved in pull request https://github.com/tbabej/django-avatar/pull/6.

It has been solved using a call to render_to_string but I think there should be only one function responsible for displaying the img HTML tag.

**Comment by Afnarel** [comment]
I just saw that the fork at https://github.com/tbabej/django-avatar seems to be the most updated version of django-avatar. If this is the case, maybe the PyPI page should be updated.

**Comment by grantmcconnaughey** [comment]
Hi there. Django-avatar is now back in action. An updated version has been deployed to PyPI and the admin issue has been fixed.
